spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Liquibase управляет схемой
    show-sql: true
  liquibase:
    change-log: classpath:db/migration/changelog-master.yml

server:
  port: 8081


jwt:
  secret: K7mN9pQ2vL8jR4tY5uI6oP1wQ3eA8xZ9oX7kP9mQ2vL8jR4tY   # Длина ключа должна быть >= 256 бит
  expiration: 3600000 # 1 часа в миллисекундах

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true

encryption:
  key:     Kj8pLm9nQ2vX4yZ8aB5cD6eF7gH9iJ0k